// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/companieshouse/payment-reconciler/app/service (interfaces: Service)

// Package service is a generated GoMock package.
package service

import (
	models "github.com/companieshouse/payment-reconciler/app/models"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockService is a mock of Service interface
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetProductsCSV mocks base method
func (m *MockService) GetProductsCSV(arg0 *models.ReconciliationMetaData) (models.CSV, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductsCSV", arg0)
	ret0, _ := ret[0].(models.CSV)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductsCSV indicates an expected call of GetProductsCSV
func (mr *MockServiceMockRecorder) GetProductsCSV(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductsCSV", reflect.TypeOf((*MockService)(nil).GetProductsCSV), arg0)
}

// GetTransactionsCSV mocks base method
func (m *MockService) GetTransactionsCSV(arg0 *models.ReconciliationMetaData) (models.CSV, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionsCSV", arg0)
	ret0, _ := ret[0].(models.CSV)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionsCSV indicates an expected call of GetTransactionsCSV
func (mr *MockServiceMockRecorder) GetTransactionsCSV(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionsCSV", reflect.TypeOf((*MockService)(nil).GetTransactionsCSV), arg0)
}
