// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/companieshouse/payment-reconciler/app/dao (interfaces: DAO)
package dao

import (
	reflect "reflect"

	models "github.com/companieshouse/payment-reconciler/app/models"
	gomock "github.com/golang/mock/gomock"
)

// MockDAO is a mock of DAO interface
type MockDAO struct {
	ctrl     *gomock.Controller
	recorder *MockDAOMockRecorder
}

// MockDAOMockRecorder is the mock recorder for MockDAO
type MockDAOMockRecorder struct {
	mock *MockDAO
}

// NewMockDAO creates a new mock instance
func NewMockDAO(ctrl *gomock.Controller) *MockDAO {
	mock := &MockDAO{ctrl: ctrl}
	mock.recorder = &MockDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDAO) EXPECT() *MockDAOMockRecorder {
	return m.recorder
}

// GetProductsData mocks base method
func (m *MockDAO) GetProductsData() (models.ProductsData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductsData")
	ret0, _ := ret[0].(models.ProductsData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductsData indicates an expected call of GetProductsData
func (mr *MockDAOMockRecorder) GetProductsData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductsData", reflect.TypeOf((*MockDAO)(nil).GetProductsData))
}

// GetTransactionsData mocks base method
func (m *MockDAO) GetTransactionsData() (models.TransactionsData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionsData")
	ret0, _ := ret[0].(models.TransactionsData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionsData indicates an expected call of GetTransactionsData
func (mr *MockDAOMockRecorder) GetTransactionsData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionsData", reflect.TypeOf((*MockDAO)(nil).GetTransactionsData))
}
