variable handler {}
variable memory_megabytes {}
variable release_bucket_name {}
variable runtime {}
variable timeout_seconds {}
variable service {}
variable release_version {}
variable execution_role {}
variable subnet_ids {}
variable security_group_ids {}
variable environment {}
variable workspace_key_prefix {}